db.getCollection('restaurant').find({});
db.getCollection('restaurant').find({},{restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({},{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({},{_id: 0,restaurant_id: 1,name: 1,borough: 1,'address.zipcode': 1});
db.getCollection('restaurant').find({borough: 'Bronx'});
db.getCollection('restaurant').find({ borough: 'Bronx' }).limit(5);
db.getCollection('restaurant').find({ borough: 'Bronx' }).limit(5).skip(5);
db.getCollection('restaurant').find({'grades.score': { $gt: 90 }});
db.getCollection('restaurant').find({'grades.score': { $gt: 80, $lt: 100 }});
db.getCollection('restaurant').find({'address.coord.0': { $lt: -95.754168 }});
db.getCollection('restaurant').find({cuisine: { $ne: 'American' },'grades.score': { $gt: 70 },'address.coord.0': { $lt: -65.754168 }});
db.getCollection('restaurant').find({cuisine: { $ne: 'American' },'grades.score': { $gt: 70 },'address.coord.0': { $lt: -65.754168 }});
db.getCollection('restaurant').find({cuisine: { $ne: 'American' },'grades.grade': 'A',borough: { $ne: 'Brooklyn' }}).sort({ cuisine: -1 });
db.getCollection('restaurant').find({ name: { $regex: '^Wil', $options: 'i' } },{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({ name: { $regex: 'ces$', $options: 'i' } },{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({ name: { $regex: 'Reg', $options: 'i' } },{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({borough: 'Bronx',cuisine: { $in: ['American', 'Chinese'] }});
db.getCollection('restaurant').find({borough: {$in: ['Staten Island','Queens','Bronx','Brooklyn']}},{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({borough: {$nin: ['Staten Island','Queens','Bronx','Brooklyn']}},{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
db.getCollection('restaurant').find({ 'grades.score': { $not: { $gt: 10 } } },{_id: 0,restaurant_id: 1,name: 1,borough: 1,cuisine: 1});
